/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as QuejasRouteImport } from './routes/quejas'
import { Route as ProduccionRouteImport } from './routes/produccion'
import { Route as PrediccionRouteImport } from './routes/prediccion'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'

const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuejasRoute = QuejasRouteImport.update({
  id: '/quejas',
  path: '/quejas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduccionRoute = ProduccionRouteImport.update({
  id: '/produccion',
  path: '/produccion',
  getParentRoute: () => rootRouteImport,
} as any)
const PrediccionRoute = PrediccionRouteImport.update({
  id: '/prediccion',
  path: '/prediccion',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/inventario': typeof InventarioRoute
  '/prediccion': typeof PrediccionRoute
  '/produccion': typeof ProduccionRoute
  '/quejas': typeof QuejasRoute
  '/reportes': typeof ReportesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/inventario': typeof InventarioRoute
  '/prediccion': typeof PrediccionRoute
  '/produccion': typeof ProduccionRoute
  '/quejas': typeof QuejasRoute
  '/reportes': typeof ReportesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/inventario': typeof InventarioRoute
  '/prediccion': typeof PrediccionRoute
  '/produccion': typeof ProduccionRoute
  '/quejas': typeof QuejasRoute
  '/reportes': typeof ReportesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/inventario'
    | '/prediccion'
    | '/produccion'
    | '/quejas'
    | '/reportes'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/inventario'
    | '/prediccion'
    | '/produccion'
    | '/quejas'
    | '/reportes'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/inventario'
    | '/prediccion'
    | '/produccion'
    | '/quejas'
    | '/reportes'
    | '/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  InventarioRoute: typeof InventarioRoute
  PrediccionRoute: typeof PrediccionRoute
  ProduccionRoute: typeof ProduccionRoute
  QuejasRoute: typeof QuejasRoute
  ReportesRoute: typeof ReportesRoute
  VentasRoute: typeof VentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quejas': {
      id: '/quejas'
      path: '/quejas'
      fullPath: '/quejas'
      preLoaderRoute: typeof QuejasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produccion': {
      id: '/produccion'
      path: '/produccion'
      fullPath: '/produccion'
      preLoaderRoute: typeof ProduccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediccion': {
      id: '/prediccion'
      path: '/prediccion'
      fullPath: '/prediccion'
      preLoaderRoute: typeof PrediccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  InventarioRoute: InventarioRoute,
  PrediccionRoute: PrediccionRoute,
  ProduccionRoute: ProduccionRoute,
  QuejasRoute: QuejasRoute,
  ReportesRoute: ReportesRoute,
  VentasRoute: VentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
